server:
  port: 7000
  servlet:
    context-path: /ad-sponsor

spring:
  application:
    name: eureka-client-ad-sponsor
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/imooc_ad?autoReconnect=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2
    driver-class-name: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/
